### ISSUE TITLE
Could not install package 'OSCforPCL 0.0.1'. 

### ISSUE THREAD

**Issue by cyrsis** [iKadmium/OSCforPCL#1]
Could not install package 'OSCforPCL 0.0.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Will it available in 4.5?

**Comment by iKadmium** [comment]
Hi there,

I'm sorry, but I'm afraid it probably won't be. "OSCforPCL" has turned out to be a very misleading name; the project targets .NET Core, rather than PCL.

**Comment by cyrsis** [comment]
Thanks buddy

I actually got it working under PCL, it helps a lot for the OSC transfer
